### PR TITLE
Prepared rootless container

### PR DESCRIPTION
**Pull request by lqb**

### CODE REVIEW

**Comment by casabre** [comment]
@lqb thanks for your contribution :partying_face:. We are reviewing your changes this week and keeping you posted. 

But there was one change which breaks current behavior &rarr; the `ARG PYTHON_INTERPRETER="python"` was set by purpose because users can switch to a `pypy` container too. Could you please revert this removal.

Thanks & best regards

**Comment by lqb** [comment]
Reverted. But I don't like it because build output is confusing
```
$ docker build --build-arg PYTHON_INTERPRETER="pypy" --build-arg=PYTHON_VERSION=3.7-slim --tag rsvisa-python:3.7-slim-5.12.3 .
Sending build context to Docker daemon    234kB
Step 1/8 : ARG PYTHON_INTERPRETER="python"
Step 2/8 : ARG PYTHON_VERSION="3.8-slim"
Step 3/8 : FROM ${PYTHON_INTERPRETER}:${PYTHON_VERSION}
3.7-slim: Pulling from library/pypy
Digest: sha256:296481c35a8a913adfb10179e66d3d009bc1d5dc62ce710187304b555c7b71bb
Status: Downloaded newer image for pypy:3.7-slim
```

**Comment by casabre** [comment]
@lqb fair enough but how can we give the flexibility to choose between `python` and `pypy`? Maybe you have another idea?!

**Comment by lqb** [comment]
I usualy avoid using ARGs and seperate them in multiple repositories or somtimes different branches. Every new version is a change in the Dockerfile and a new commit. 
Another way would be to use uninitalized ARGS. But then you can't build without specifying them on the commandline.

**Review by casabre — APPROVED** [review]

**Pull request merged**
